[package]
name = "wasm-oauth2"
version = "0.1.0"
authors = ["Your Name"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.78"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.12.6"
wasm-bindgen-futures = "0.4.23"
web-sys = "0.3"
